from __future__ import annotations

import json
import re
import subprocess
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OCR_DATA = ROOT / "playable" / "book-data.js"
OCR_PAGES = ROOT / "playable" / "pages.txt"
FALLBACK_DATA = ROOT / "tools" / "embedded-cache" / "book-data.js"


def load_js_data(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    match = re.search(r"window\.GAMEBOOK_DATA\s*=\s*(.*);\s*$", text, re.S)
    if not match:
        raise ValueError(f"Could not read data from {path}")
    try:
        return json.loads(match.group(1))
    except json.JSONDecodeError:
        node = Path(r"C:\Program Files\nodejs\node.exe")
        script = (
            "global.window={};"
            f"require({json.dumps(str(path))});"
            "process.stdout.write(JSON.stringify(window.GAMEBOOK_DATA));"
        )
        output = subprocess.check_output([str(node), "-e", script], cwd=ROOT)
        return json.loads(output.decode("utf-8"))


def clean_intro(text: str) -> str:
    lines = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line:
            lines.append("")
            continue
        if re.fullmatch(r"[-=_ .,'\"|\\/()A-Za-z]{1,30}", line) and len(re.findall(r"[A-Za-z]{3,}", line)) == 0:
            continue
        if re.fullmatch(r"\d{1,2}", line):
            continue
        lines.append(line)

    value = "\n".join(lines)
    value = re.sub(r"\n{3,}", "\n\n", value)
    value = value.replace("Now tum to paragraph 1", "Now turn to paragraph 1")
    value = value.replace("sraMina", "STAMINA")
    value = value.replace("LucK", "LUCK")
    return value.strip()


def token_to_section(token: str) -> int | None:
    clean = re.sub(r"[^\w()%]", "", token)
    if clean.isdigit():
        value = int(clean)
        return value if 1 <= value <= 400 else None

    mapping = {
        "O": "0",
        "o": "0",
        "Q": "0",
        "I": "1",
        "l": "1",
        "i": "1",
        "a": "1",
        "A": "1",
        "%": "1",
        "S": "5",
        "s": "5",
        "B": "8",
        "g": "9",
        "q": "9",
    }
    digits = "".join(char if char.isdigit() else mapping.get(char, "") for char in clean)
    if not digits:
        return None
    value = int(re.sub(r"00+", "0", digits))
    return value if 1 <= value <= 400 else None


def section_references(text: str, current: int) -> list[int]:
    refs = []
    seen = set()
    pattern = re.compile(
        r"\b(?:turn|tum|tuin|tuln|furn|fum|hrm|rurn|go|return|continue)\s+(?:to|at)?\s*([0-9OoQIiLlAaEeSsBbGgqQjJzZ()%{}.,'\"]{1,6})",
        re.I,
    )
    for match in pattern.finditer(text):
        target = token_to_section(match.group(1))
        if target and target != current and target not in seen:
            refs.append(target)
            seen.add(target)
    return refs


def intro_from_pages(path: Path, section_one_page: int) -> str:
    text = path.read_text(encoding="utf-8")
    if section_one_page <= 1:
        return ""
    chunks = re.split(r"\n\s*--- PAGE BREAK ---\s*\n", text)
    intro_pages = chunks[: section_one_page - 1]
    return clean_intro("\n".join(intro_pages))


def main() -> int:
    data = load_js_data(OCR_DATA)
    fallback = load_js_data(FALLBACK_DATA) if FALLBACK_DATA.exists() else {"sections": {}}
    fallback_count = 0

    for number in range(1, 401):
        key = str(number)
        section = data["sections"][key]
        if section.get("text", "").strip():
            section["ocrSource"] = section.get("ocrSource") or "tesseract"
            continue

        fallback_section = fallback.get("sections", {}).get(key, {})
        if not fallback_section:
            section["ocrSource"] = "missing"
            continue
        section["text"] = fallback_section.get("text", "")
        section["choices"] = fallback_section.get("choices", [])
        section["page"] = fallback_section.get("page", section.get("page", 1))
        section["ocrSource"] = "embedded-fallback"
        fallback_count += 1

    for number in range(1, 401):
        section = data["sections"][str(number)]
        section["text"] = re.sub(rf"^\s*{number}\s+", "", section.get("text", "")).strip()
        section["choices"] = section_references(section["text"], number)

    total_fallback = sum(
        1 for section in data["sections"].values() if section.get("ocrSource") == "embedded-fallback"
    )
    total_missing = sum(
        1 for section in data["sections"].values() if not section.get("text", "").strip()
    )

    section_one_page = data["sections"]["1"].get("page", 1) or 1
    data["intro"] = {
        "title": "Introduction",
        "page": 1,
        "text": intro_from_pages(OCR_PAGES, section_one_page),
    }
    data["note"] = (
        "Primary text was generated by fresh Tesseract OCR. "
        f"{total_fallback} sections that Tesseract did not split cleanly use the PDF's embedded OCR fallback; "
        f"{total_missing} sections still need manual OCR review."
    )

    OCR_DATA.write_text(
        "window.GAMEBOOK_DATA = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n",
        encoding="utf-8",
    )
    print(f"Fallback sections filled: {fallback_count}")
    print(f"Intro characters: {len(data['intro']['text'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
